python imdb_crawler.py "Stargate SG-1"
python imdb_crawler.py "Star Trek The Next Generation"
python imdb_crawler.py "Tim And Eric Awesome Show Great Job"
python imdb_crawler.py "Whose Line Is It Anyway 1998"
python imdb_crawler.py "Star Trek Original Series"
python imdb_crawler.py "Seinfeld"
python imdb_crawler.py "Star Trek Deep Space Nine"
python imdb_crawler.py "Stargate Atlantis"
python imdb_crawler.py "Qi"
python imdb_crawler.py "Top Gear"