
_DEBUG_MODE = False

LOG_ROLLED_PROMPT_PARAMS = False
LOG_GENERATED_TEXT = False

_AI_OPTION_OPENAI = "OPENAI"
_AI_OPTION_GEMINI = "GEMINI"
_AI_OPTION_PAWANKRD = "PAWANKRD"
_AI_OPTION_GROQ = "GROQ"

_AI_BEING_USED = _AI_OPTION_GROQ
