services:
  backend:
    build: 
      context: ./backend
      args:
        CLEAN_BUILD: "true"  # Set to "true" for a clean build
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm start
