openapi: 3.0.0
info:
  title: String Reverser API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /reverse:
    post:
      summary: Reverses the provided string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  example: hello
      responses:
        200:
          description: A string reversed
          content:
            application/json:
              schema:
                type: object
                properties:
                  reversed:
                    type: string
                    example: olleh
