openapi: "3.0.0"
info:
  title: "Genten API"
  version: "1.0.0"
servers:
  - url: "http://localhost:3001"
paths:
  /api/model:
    get:
      summary: "Get Current Model"
      operationId: "getModel"
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                type: string
    post:
      summary: "Set Current Model"
      operationId: "setModel"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: "Model Updated Successfully"

